$axure.loadCurrentPage({
  "url":"00社区app后台登录.html",
  "generationDate":new Date(1497581698026.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"264fead3e08a46529cff3cd6e4a0c568",
    "type":"Axure:Page",
    "name":"00社区APP后台登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1b36510ce5b4989b945fa64730c770b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":10},
            "size":{
              "width":970,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827b0627395a4768a3b38bf91ab93ce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":10},
                "size":{
                  "width":970,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/00社区app后台登录/u0.png"}},
{
          "id":"4478d2012c4d4bf8917e75611293cc19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":455.5,
              "y":205},
            "size":{
              "width":239,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b9a13c6406048b6ba531c5b6cf70657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":455.5,
                  "y":205},
                "size":{
                  "width":239,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/00社区app后台登录/u2.png"}},
{
          "id":"fbcda378a3f54d6e844b5afa8c312308",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":455.5,
              "y":265},
            "size":{
              "width":239,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f434f88b6aed4149b11b562ac0f7e534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":455.5,
                  "y":265},
                "size":{
                  "width":239,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/00社区app后台登录/u2.png"}},
{
          "id":"530450a50fa048499bd6b7e9602d035a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":455.5,
              "y":355},
            "size":{
              "width":239,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fb81fb3c340e4dc2b0e8ea79ad2dff26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":465.5,
              "y":215},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dab5c1f62d441418626e6653e88c58f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":465.5,
                  "y":215},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/00社区app后台登录/u7.png"}},
{
          "id":"064b9572ea534f8e88cc4b90ef4e3f9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":465.5,
              "y":271},
            "size":{
              "width":14,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab87881070c461091af6b7b36565e3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":465.5,
                  "y":271},
                "size":{
                  "width":14,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/00社区app后台登录/u9.png"}},
{
          "id":"76dbf2b3d8f044b49e2aa598290cb8f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":496,
              "y":217},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"789d7531f4794ad98f41f4dfdc02a31d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":496,
                  "y":217},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4be90ac491a4ef2b85c539580e8197f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":496,
              "y":277},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f7536731e545ffad7f9d1e5b93aa05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":496,
                  "y":277},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecd136abbb6345b79676b77783523c8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":436.5,
              "y":70},
            "size":{
              "width":278,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3572d0f5ad4c248c8917ab0f6108b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":436.5,
                  "y":70},
                "size":{
                  "width":278,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1d21777b1624e94b05688a0ad999d19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":456,
              "y":155},
            "size":{
              "width":239,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcaa103e84a746b1968e51685b483ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":456,
                  "y":155},
                "size":{
                  "width":239,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/00社区app后台登录/u17.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a1b36510ce5b4989b945fa64730c770b":{
      "scriptId":"u0"},
    "827b0627395a4768a3b38bf91ab93ce6":{
      "scriptId":"u1"},
    "4478d2012c4d4bf8917e75611293cc19":{
      "scriptId":"u2"},
    "7b9a13c6406048b6ba531c5b6cf70657":{
      "scriptId":"u3"},
    "fbcda378a3f54d6e844b5afa8c312308":{
      "scriptId":"u4"},
    "f434f88b6aed4149b11b562ac0f7e534":{
      "scriptId":"u5"},
    "530450a50fa048499bd6b7e9602d035a":{
      "scriptId":"u6"},
    "fb81fb3c340e4dc2b0e8ea79ad2dff26":{
      "scriptId":"u7"},
    "4dab5c1f62d441418626e6653e88c58f":{
      "scriptId":"u8"},
    "064b9572ea534f8e88cc4b90ef4e3f9f":{
      "scriptId":"u9"},
    "dab87881070c461091af6b7b36565e3c":{
      "scriptId":"u10"},
    "76dbf2b3d8f044b49e2aa598290cb8f5":{
      "scriptId":"u11"},
    "789d7531f4794ad98f41f4dfdc02a31d":{
      "scriptId":"u12"},
    "b4be90ac491a4ef2b85c539580e8197f":{
      "scriptId":"u13"},
    "67f7536731e545ffad7f9d1e5b93aa05":{
      "scriptId":"u14"},
    "ecd136abbb6345b79676b77783523c8f":{
      "scriptId":"u15"},
    "3f3572d0f5ad4c248c8917ab0f6108b0":{
      "scriptId":"u16"},
    "b1d21777b1624e94b05688a0ad999d19":{
      "scriptId":"u17"},
    "fcaa103e84a746b1968e51685b483ecc":{
      "scriptId":"u18"}}});