$axure.loadCurrentPage({
  "url":"copy_of_模拟量编辑ok.html",
  "generationDate":new Date(1497581713530.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c04b123ddf6d4d4e925c7c5905ee8b4a",
    "type":"Axure:Page",
    "name":"Copy of 模拟量编辑ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFD7D7D7},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cc1f726374554cb18cb710281e2d61ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":3,
              "y":68},
            "size":{
              "width":1310,
              "height":1212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de4170bbf372403e9426f2a3c01295b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":3,
                  "y":68},
                "size":{
                  "width":1310,
                  "height":1212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/精选管理（统计）/u0.png"}},
{
          "id":"6b09710372b843e3aaba0c6108fd7757",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF5E5E5E},
            "location":{
              "x":3,
              "y":1275},
            "size":{
              "width":1310,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60e8cacfcef94b9ba0f7d1ca7947659b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E},
                "location":{
                  "x":3,
                  "y":1275},
                "size":{
                  "width":1310,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/精选管理（统计）/u2.png"}},
{
          "id":"1778758790ce4ffc9fc5f084850c346a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":99},
            "size":{
              "width":10,
              "height":928},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增文章ok/u14_line.png"}},
{
          "id":"a40d63a1351b416eab6b9184fe6f578a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"400",
            "location":{
              "x":293,
              "y":121},
            "size":{
              "width":337,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236a4396b5af4308b7ac1949c3440883",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"400",
                "location":{
                  "x":293,
                  "y":121},
                "size":{
                  "width":337,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d4f67a4487b424294902c93a4f22c56",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":169},
            "size":{
              "width":1033,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增文章ok/u91_line.png"}},
{
          "id":"5a988cd8f2c6460fac502a9acfd22466",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d556c015f571493782c9945be08f66bc"},
{
          "id":"c55c0c6be9814430a0ce35cb4fa49451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":708,
              "y":1235},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ddcf0fe3cc846ef8d750de8f03e6361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":708,
                  "y":1235},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增文章ok/u713.png"}},
{
          "id":"1e1f055b8a824caf8f42d1a424e5f40f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":620,
              "y":1235},
            "size":{
              "width":70,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30cc0791fd874f08b4e03e2fb1c17b67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":620,
                  "y":1235},
                "size":{
                  "width":70,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 精选列表ok",
                      "target":{
                        "targetType":"page",
                        "url":"精选列表ok.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增文章ok/u713.png"}},
{
          "id":"105b027a3291470dbf90c7adadd41a44",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":1220},
            "size":{
              "width":1033,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增文章ok/u91_line.png"}},
{
          "id":"e51284fdb6f0481cac2980a77d86f548",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":409,
              "y":406},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a8248d6e3f404e92f69efe54b36443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":409,
                  "y":406},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c69baad394da424b9edd4bab3c316fd4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":624,
              "y":407},
            "size":{
              "width":14,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增文章ok/u657_line.png"}},
{
          "id":"d4f787bcff9a41598417047367d18d23",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":638,
              "y":400},
            "size":{
              "width":134,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fd3802ccd8024495af23aada23074775",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":370,
              "y":463},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f7dcec4e7f34821babdd260c214838f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":370,
                  "y":463},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e61ba82467b4b738d2a84d38a80f652",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":397,
              "y":406},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00782283b05446b9867647d67a3971c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":397,
                  "y":406},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"711239290b7b424489b44e624ad2f799",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":521,
              "y":459},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"178af0dc163f4d0f99b0ce50539775b9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":466},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增文章ok/u666_line.png"}},
{
          "id":"20cc74f7521d47a28aa6a706ea308a36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":409,
              "y":349},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c791f36a026e46298029ce2078b92a3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":409,
                  "y":349},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c46ebdc205254b90a9274d5e2858c269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":396,
              "y":351},
            "size":{
              "width":31,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"614df30434c44a7b93f6457ced160d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":396,
                  "y":351},
                "size":{
                  "width":31,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fc09c560ef54ee2b09521b8d5290476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":322,
              "y":200},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9de8157f80a3451f8b1674e74e0e6f2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":322,
                  "y":200},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cfecdbc38a24de28626e1973fc60b13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":322,
              "y":521},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"072c831dda6541e69105371bc6f3f66f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":322,
                  "y":521},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f7febf09bd04e53b6261cf8c32b885e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":409,
              "y":653},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d86a5d843d04843b736112c950959f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":409,
                  "y":653},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4f78b1f7bdc47cc970cba64204cea6a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":490,
              "y":347},
            "size":{
              "width":134,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e355bba355d14b55b1e40592bd5e683e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":421,
              "y":200},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b9295261491403cbc6fbca5b13ab120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":421,
                  "y":200},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f5af34c95f343f9be7165420dca38dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":435,
              "y":247},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581bf86880ee4f4990f361760b0ff01b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":435,
                  "y":247},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29403bd94f9048a5afee5dab0403418a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":247},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df855e2dafd4193a27aaccfa9345570",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":247},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3343d77ad315479da99da66ba86964e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":435,
              "y":281},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6df80556de44bcf9efafe783b06c967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":435,
                  "y":281},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"304930366533453e86f7cf7ea6074e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":281},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ec9ced17954f09afc25e5bf8d248d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":281},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28dbd6667d404649a38126c9d64360ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":435,
              "y":551},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff1f3873c68446f1a1e008e131abe9fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":435,
                  "y":551},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b24a0cc1317e452a98ec528c79f9bbc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":551},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ac3890c8b4425387ac9f096d3836ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":551},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82f566a91cdb49f9bb8eee00f92d9321",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":435,
              "y":585},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67d179115f4485aa2c2666c051560f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":435,
                  "y":585},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dce686a715aa4deaa488a4c21e685fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":585},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f957c860ccc848ff9b1849a204dc30ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":585},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc0a383b5bc64f778dcf44be7a66308d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":490,
              "y":400},
            "size":{
              "width":134,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"25084e3ff56542ffb420c11bb424a584",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":463},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"072d00a4aadd4f6287de14a7a0fbc227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":463},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edfaeb636bc64f61bdb3cfcd528325d6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":521,
              "y":648},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"06b907830a5247a8a99346243be6f26a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":656},
            "size":{
              "width":20,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增文章ok/u666_line.png"}},
{
          "id":"3f6979b7ce214bdf86248a525ebd2234",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":652},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db87a81b3284d9e9deb739308415d1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":652},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0592bf91e754d77aa58dd1ceac21003",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":617,
              "y":455},
            "size":{
              "width":323,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8335f24320ef43eba90f1cd080fd9d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":455},
                "size":{
                  "width":323,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c250c56897954753bcea70b1bf1f1a72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":617,
              "y":645},
            "size":{
              "width":303,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2853817b09e94c6895c8a9b836f042ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":645},
                "size":{
                  "width":303,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"272b5bc952f9433ba693df00b9530906",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":422,
              "y":314},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ad7104b4684467b89d81635ccee9728",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":422,
                  "y":314},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d48c1ec3f6f4fa9be74081d7d0c273b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":314},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ac65d0705e421d904bcd24405600b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":314},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"009027c8d46d4374973354a3985f6cbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":423,
              "y":617},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa241ff301843bc8ee78d205d81a3e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":423,
                  "y":617},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb67ad2078694d05a0fa5077ac64f1ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":490,
              "y":617},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10d0836155174346b7b4806b0fc2cb1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":490,
                  "y":617},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d16bf0e0d18e495cbeb42b6a4e2c8f33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":825,
              "y":352},
            "size":{
              "width":95,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e26e618ba4744a9ac1a5331703683de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":825,
                  "y":352},
                "size":{
                  "width":95,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2803da4999b044c688e8cf92f197bf1d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":645,
              "y":347},
            "size":{
              "width":48,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fb85c2b144dd4d758fd56af37ffa3ea2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":703,
              "y":347},
            "size":{
              "width":48,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d10daccf51c44097bbfc96ccf2d93d81",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":761,
              "y":347},
            "size":{
              "width":48,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d549d507c2814bf59f6bb5f7d59a879b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":624,
              "y":352},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a0d248213284c9086426dd1e0dd29f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":624,
                  "y":352},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bce99a6a245e47d98c3929ca124b32e1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":3,
              "y":1360},
            "size":{
              "width":739,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a9cfc7017124bb99134e0dac64a7667",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":117,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9c68eb906f14515afb73d46221b92d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":117,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/精选列表ok/u364.png"}},
{
              "id":"372f9368a4694fdabc89f0808b745a31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":117,
                  "y":0},
                "size":{
                  "width":622,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"050179aa44994bd3b1c023ba186249c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":117,
                      "y":0},
                    "size":{
                      "width":622,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/copy_of_正在增长列表ok/u321.png"}},
{
              "id":"1402eeee137b4af3b3c203f608c30ce8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":117,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3669875cd7e44decb1bd2334c3d1df7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":68},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/定时任务ok/u264.png"}},
{
              "id":"1d6e01d1ffc740c7a24478bb908f1116",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":117,
                  "y":30},
                "size":{
                  "width":622,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ccf0226f1414fbe9980b769341643de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":117,
                      "y":30},
                    "size":{
                      "width":622,
                      "height":68},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/copy_of_正在增长列表ok/u325.png"}}]}]}},
  "masters":{
    "d556c015f571493782c9945be08f66bc":{
      "packageId":"d556c015f571493782c9945be08f66bc",
      "type":"Axure:Master",
      "name":"精选母版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"65c7a62f016d48ee84560a4f87531b5b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF5E5E5E},
              "size":{
                "width":1310,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF5E5E5E}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b65745dc4fcf40a4ba93cbf752242d64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF5E5E5E},
                  "size":{
                    "width":1310,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF5E5E5E}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/精选管理（统计）/u99.png"}},
{
            "id":"3c6a24f1465e454c90b51d8b9cca8fc3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":20,
                "y":23},
              "size":{
                "width":139,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2b7e8da32d43453898199f1a42607785",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":20,
                    "y":23},
                  "size":{
                    "width":139,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c2fce3f31266476da2a0d544c1717e60",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":30,
                "y":110},
              "size":{
                "width":247,
                "height":560},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2171f721c40c40fd8759cc33ac6f9979",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":30,
                    "y":110},
                  "size":{
                    "width":247,
                    "height":560},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/精选管理（统计）/u103.png"}},
{
            "id":"c522b27a68d649d8ab52519cde771cb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1130,
                "y":32},
              "size":{
                "width":140,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"124af8cea5f7493bab98b469161b19d6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1130,
                    "y":32},
                  "size":{
                    "width":140,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"73be829478964b63a76251f834ccb049",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":60,
                "y":130},
              "size":{
                "width":34,
                "height":34}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7a77f3631b541d18d94e7f3f09a6245",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":60,
                    "y":130},
                  "size":{
                    "width":34,
                    "height":34}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/精选管理（统计）/u107.png"}},
{
            "id":"0213fdccaf6b41139f8862d8aee33d2d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":104,
                "y":132},
              "size":{
                "width":49,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"15865d0d816a426f8a5939dc76950a1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":104,
                    "y":132},
                  "size":{
                    "width":49,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"69c7b8d2dad440df9c0dfa19ba48b6a8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontWeight":"400",
              "location":{
                "x":105,
                "y":360},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e2aea17624a41cd85b364b5070269cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontWeight":"400",
                  "location":{
                    "x":105,
                    "y":360},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 社区管理（统计）",
                        "target":{
                          "targetType":"page",
                          "url":"社区管理（统计）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"162c54ddcf6946a69c4d6a1ed5408176",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontWeight":"400",
              "location":{
                "x":105,
                "y":412},
              "size":{
                "width":121,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1098bf7d91e3473884f124aa58e7f392",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontWeight":"400",
                  "location":{
                    "x":105,
                    "y":412},
                  "size":{
                    "width":121,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 banner管理-已发布ok",
                        "target":{
                          "targetType":"page",
                          "url":"banner__-___ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3be003be344f4a9c97f6131cc47853ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "location":{
                "x":105,
                "y":180},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b4c6eaf79c704b4791cd8f470edca62e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "location":{
                    "x":105,
                    "y":180},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 社区管理（统计）",
                        "target":{
                          "targetType":"page",
                          "url":"社区管理（统计）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d3485a0a51ee4d2bb2b81cf3db52e067",
            "label":"广告位管理",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":128,
                "y":416},
              "size":{
                "width":100,
                "height":158},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"隐藏 广告位管理",
                        "objectsToFades":[{
                            "objectPath":["d3485a0a51ee4d2bb2b81cf3db52e067"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"ac0b99aa21984c64bea3511ff53a53a8",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"cf5daf078ca64dea9ee41bf1ef3ef4ac",
                    "label":"",
                    "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontWeight":"400",
                      "location":{
                        "x":3,
                        "y":0},
                      "size":{
                        "width":121,
                        "height":28}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d9f6b377394342b782428ab668131488",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"400",
                          "location":{
                            "x":3,
                            "y":0},
                          "size":{
                            "width":121,
                            "height":28}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 banner管理-已发布ok",
                                "target":{
                                  "targetType":"page",
                                  "url":"banner__-___ok.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"显示 (表格)",
                                "objectsToFades":[{
                                    "objectPath":["07ffcc53ac7e4e9c8b76132971daf229"],
                                    "fadeInfo":{
                                      "fadeType":"show",
                                      "options":{
                                        "showType":"none"}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"隐藏 (表格)",
                                "objectsToFades":[{
                                    "objectPath":["07ffcc53ac7e4e9c8b76132971daf229"],
                                    "fadeInfo":{
                                      "fadeType":"hide",
                                      "options":{
                                        "showType":"none"}}}]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"07ffcc53ac7e4e9c8b76132971daf229",
                    "label":"",
                    "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":0,
                        "y":38},
                      "size":{
                        "width":100,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d0c428069ef3415d94f02d56c3d856d1",
                        "label":"",
                        "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "size":{
                            "width":100,
                            "height":30}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"4dfab91b253f4076953f5c0f374611cf",
                            "label":"",
                            "isContained":true,
                            "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "size":{
                                "width":100,
                                "height":30}},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"Case 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"在 当前窗口 打开 banner管理-已发布ok",
                                    "target":{
                                      "targetType":"page",
                                      "url":"banner__-___ok.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/精选管理（统计）/u121.png"}},
{
                        "id":"d2d68873a3c24baba40bf036a5c1b5a4",
                        "label":"",
                        "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "location":{
                            "x":0,
                            "y":30},
                          "size":{
                            "width":100,
                            "height":30}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"9393775978be444d8ce0eb85117ea465",
                            "label":"",
                            "isContained":true,
                            "parentDynamicPanel":"d3485a0a51ee4d2bb2b81cf3db52e067",
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "location":{
                                "x":0,
                                "y":30},
                              "size":{
                                "width":100,
                                "height":30}},
                            "adaptiveStyles":{
}}],
                        "interactionMap":{
                          "onClick":{
                            "description":"OnClick",
                            "cases":[{
                                "description":"Case 1",
                                "isNewIfGroup":false,
                                "actions":[{
                                    "action":"linkWindow",
                                    "description":"在 当前窗口 打开 广告管理-已发布ok",
                                    "target":{
                                      "targetType":"page",
                                      "url":"广告管理-已发布ok.html",
                                      "includeVariables":true},
                                    "linkType":"current"}]}]}},
                        "tabbable":true,
                        "images":{
                          "normal~":"images/精选管理（统计）/u123.png"}}]}]}]},
{
            "id":"be1382d1788e4e5fb544cff1696e626e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontWeight":"400",
              "location":{
                "x":105,
                "y":470},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4ef8f30ecb7b4f4ca85475347f0d4110",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontWeight":"400",
                  "location":{
                    "x":105,
                    "y":470},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 banner管理-已发布ok",
                        "target":{
                          "targetType":"page",
                          "url":"banner__-___ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e510f75e4c7f48708de3d980ddaa98b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":149,
                "y":218},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef1c2c00a8bc49eaab6eadc5d7abdc4e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":149,
                    "y":218},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 精选列表ok",
                        "target":{
                          "targetType":"page",
                          "url":"精选列表ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9c9d94c2f9db47738458e31174848454",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":149,
                "y":244},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e51b6d6370f541a1a30842d7bafb3c49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":149,
                    "y":244},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 定时任务OK",
                        "target":{
                          "targetType":"page",
                          "url":"定时任务ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c100fe0c1a31407bb4e035ffdbee6a08",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":149,
                "y":270},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87f942ea653d4c0b8ec027e488ce656e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":149,
                    "y":270},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 待审核列表OK",
                        "target":{
                          "targetType":"page",
                          "url":"待审核列表ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"85ccbb2fe7104f5eb5d2b95de183c2ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":149,
                "y":296},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f07500800e47421cb307fba15f3b8043",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":149,
                    "y":296},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 素材列表OK",
                        "target":{
                          "targetType":"page",
                          "url":"素材列表ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6b27070e32cd4fbd8e0166080fd9529e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":137,
                "y":322},
              "size":{
                "width":66,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5bd3ce947c04158905c5f8afa5c7a13",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":137,
                    "y":322},
                  "size":{
                    "width":66,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 正在增长列表ok",
                        "target":{
                          "targetType":"page",
                          "url":"正在增长列表ok.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "cc1f726374554cb18cb710281e2d61ec":{
      "scriptId":"u0"},
    "de4170bbf372403e9426f2a3c01295b1":{
      "scriptId":"u1"},
    "6b09710372b843e3aaba0c6108fd7757":{
      "scriptId":"u2"},
    "60e8cacfcef94b9ba0f7d1ca7947659b":{
      "scriptId":"u3"},
    "1778758790ce4ffc9fc5f084850c346a":{
      "scriptId":"u4"},
    "a40d63a1351b416eab6b9184fe6f578a":{
      "scriptId":"u5"},
    "236a4396b5af4308b7ac1949c3440883":{
      "scriptId":"u6"},
    "6d4f67a4487b424294902c93a4f22c56":{
      "scriptId":"u7"},
    "5a988cd8f2c6460fac502a9acfd22466":{
      "scriptId":"u8",
      "65c7a62f016d48ee84560a4f87531b5b":{
        "scriptId":"u9"},
      "b65745dc4fcf40a4ba93cbf752242d64":{
        "scriptId":"u10"},
      "3c6a24f1465e454c90b51d8b9cca8fc3":{
        "scriptId":"u11"},
      "2b7e8da32d43453898199f1a42607785":{
        "scriptId":"u12"},
      "c2fce3f31266476da2a0d544c1717e60":{
        "scriptId":"u13"},
      "2171f721c40c40fd8759cc33ac6f9979":{
        "scriptId":"u14"},
      "c522b27a68d649d8ab52519cde771cb3":{
        "scriptId":"u15"},
      "124af8cea5f7493bab98b469161b19d6":{
        "scriptId":"u16"},
      "73be829478964b63a76251f834ccb049":{
        "scriptId":"u17"},
      "c7a77f3631b541d18d94e7f3f09a6245":{
        "scriptId":"u18"},
      "0213fdccaf6b41139f8862d8aee33d2d":{
        "scriptId":"u19"},
      "15865d0d816a426f8a5939dc76950a1b":{
        "scriptId":"u20"},
      "69c7b8d2dad440df9c0dfa19ba48b6a8":{
        "scriptId":"u21"},
      "4e2aea17624a41cd85b364b5070269cc":{
        "scriptId":"u22"},
      "162c54ddcf6946a69c4d6a1ed5408176":{
        "scriptId":"u23"},
      "1098bf7d91e3473884f124aa58e7f392":{
        "scriptId":"u24"},
      "3be003be344f4a9c97f6131cc47853ce":{
        "scriptId":"u25"},
      "b4c6eaf79c704b4791cd8f470edca62e":{
        "scriptId":"u26"},
      "d3485a0a51ee4d2bb2b81cf3db52e067":{
        "scriptId":"u27"},
      "cf5daf078ca64dea9ee41bf1ef3ef4ac":{
        "scriptId":"u28"},
      "d9f6b377394342b782428ab668131488":{
        "scriptId":"u29"},
      "07ffcc53ac7e4e9c8b76132971daf229":{
        "scriptId":"u30"},
      "d0c428069ef3415d94f02d56c3d856d1":{
        "scriptId":"u31"},
      "4dfab91b253f4076953f5c0f374611cf":{
        "scriptId":"u32"},
      "d2d68873a3c24baba40bf036a5c1b5a4":{
        "scriptId":"u33"},
      "9393775978be444d8ce0eb85117ea465":{
        "scriptId":"u34"},
      "be1382d1788e4e5fb544cff1696e626e":{
        "scriptId":"u35"},
      "4ef8f30ecb7b4f4ca85475347f0d4110":{
        "scriptId":"u36"},
      "e510f75e4c7f48708de3d980ddaa98b9":{
        "scriptId":"u37"},
      "ef1c2c00a8bc49eaab6eadc5d7abdc4e":{
        "scriptId":"u38"},
      "9c9d94c2f9db47738458e31174848454":{
        "scriptId":"u39"},
      "e51b6d6370f541a1a30842d7bafb3c49":{
        "scriptId":"u40"},
      "c100fe0c1a31407bb4e035ffdbee6a08":{
        "scriptId":"u41"},
      "87f942ea653d4c0b8ec027e488ce656e":{
        "scriptId":"u42"},
      "85ccbb2fe7104f5eb5d2b95de183c2ca":{
        "scriptId":"u43"},
      "f07500800e47421cb307fba15f3b8043":{
        "scriptId":"u44"},
      "6b27070e32cd4fbd8e0166080fd9529e":{
        "scriptId":"u45"},
      "d5bd3ce947c04158905c5f8afa5c7a13":{
        "scriptId":"u46"}},
    "c55c0c6be9814430a0ce35cb4fa49451":{
      "scriptId":"u47"},
    "8ddcf0fe3cc846ef8d750de8f03e6361":{
      "scriptId":"u48"},
    "1e1f055b8a824caf8f42d1a424e5f40f":{
      "scriptId":"u49"},
    "30cc0791fd874f08b4e03e2fb1c17b67":{
      "scriptId":"u50"},
    "105b027a3291470dbf90c7adadd41a44":{
      "scriptId":"u51"},
    "e51284fdb6f0481cac2980a77d86f548":{
      "scriptId":"u52"},
    "76a8248d6e3f404e92f69efe54b36443":{
      "scriptId":"u53"},
    "c69baad394da424b9edd4bab3c316fd4":{
      "scriptId":"u54"},
    "d4f787bcff9a41598417047367d18d23":{
      "scriptId":"u55"},
    "fd3802ccd8024495af23aada23074775":{
      "scriptId":"u56"},
    "7f7dcec4e7f34821babdd260c214838f":{
      "scriptId":"u57"},
    "2e61ba82467b4b738d2a84d38a80f652":{
      "scriptId":"u58"},
    "00782283b05446b9867647d67a3971c5":{
      "scriptId":"u59"},
    "711239290b7b424489b44e624ad2f799":{
      "scriptId":"u60"},
    "178af0dc163f4d0f99b0ce50539775b9":{
      "scriptId":"u61"},
    "20cc74f7521d47a28aa6a706ea308a36":{
      "scriptId":"u62"},
    "c791f36a026e46298029ce2078b92a3a":{
      "scriptId":"u63"},
    "c46ebdc205254b90a9274d5e2858c269":{
      "scriptId":"u64"},
    "614df30434c44a7b93f6457ced160d3c":{
      "scriptId":"u65"},
    "2fc09c560ef54ee2b09521b8d5290476":{
      "scriptId":"u66"},
    "9de8157f80a3451f8b1674e74e0e6f2e":{
      "scriptId":"u67"},
    "8cfecdbc38a24de28626e1973fc60b13":{
      "scriptId":"u68"},
    "072c831dda6541e69105371bc6f3f66f":{
      "scriptId":"u69"},
    "9f7febf09bd04e53b6261cf8c32b885e":{
      "scriptId":"u70"},
    "1d86a5d843d04843b736112c950959f5":{
      "scriptId":"u71"},
    "c4f78b1f7bdc47cc970cba64204cea6a":{
      "scriptId":"u72"},
    "e355bba355d14b55b1e40592bd5e683e":{
      "scriptId":"u73"},
    "2b9295261491403cbc6fbca5b13ab120":{
      "scriptId":"u74"},
    "5f5af34c95f343f9be7165420dca38dd":{
      "scriptId":"u75"},
    "581bf86880ee4f4990f361760b0ff01b":{
      "scriptId":"u76"},
    "29403bd94f9048a5afee5dab0403418a":{
      "scriptId":"u77"},
    "2df855e2dafd4193a27aaccfa9345570":{
      "scriptId":"u78"},
    "3343d77ad315479da99da66ba86964e3":{
      "scriptId":"u79"},
    "e6df80556de44bcf9efafe783b06c967":{
      "scriptId":"u80"},
    "304930366533453e86f7cf7ea6074e15":{
      "scriptId":"u81"},
    "71ec9ced17954f09afc25e5bf8d248d2":{
      "scriptId":"u82"},
    "28dbd6667d404649a38126c9d64360ed":{
      "scriptId":"u83"},
    "ff1f3873c68446f1a1e008e131abe9fd":{
      "scriptId":"u84"},
    "b24a0cc1317e452a98ec528c79f9bbc7":{
      "scriptId":"u85"},
    "e4ac3890c8b4425387ac9f096d3836ae":{
      "scriptId":"u86"},
    "82f566a91cdb49f9bb8eee00f92d9321":{
      "scriptId":"u87"},
    "e67d179115f4485aa2c2666c051560f8":{
      "scriptId":"u88"},
    "dce686a715aa4deaa488a4c21e685fcb":{
      "scriptId":"u89"},
    "f957c860ccc848ff9b1849a204dc30ed":{
      "scriptId":"u90"},
    "dc0a383b5bc64f778dcf44be7a66308d":{
      "scriptId":"u91"},
    "25084e3ff56542ffb420c11bb424a584":{
      "scriptId":"u92"},
    "072d00a4aadd4f6287de14a7a0fbc227":{
      "scriptId":"u93"},
    "edfaeb636bc64f61bdb3cfcd528325d6":{
      "scriptId":"u94"},
    "06b907830a5247a8a99346243be6f26a":{
      "scriptId":"u95"},
    "3f6979b7ce214bdf86248a525ebd2234":{
      "scriptId":"u96"},
    "2db87a81b3284d9e9deb739308415d1c":{
      "scriptId":"u97"},
    "a0592bf91e754d77aa58dd1ceac21003":{
      "scriptId":"u98"},
    "8335f24320ef43eba90f1cd080fd9d12":{
      "scriptId":"u99"},
    "c250c56897954753bcea70b1bf1f1a72":{
      "scriptId":"u100"},
    "2853817b09e94c6895c8a9b836f042ad":{
      "scriptId":"u101"},
    "272b5bc952f9433ba693df00b9530906":{
      "scriptId":"u102"},
    "6ad7104b4684467b89d81635ccee9728":{
      "scriptId":"u103"},
    "7d48c1ec3f6f4fa9be74081d7d0c273b":{
      "scriptId":"u104"},
    "85ac65d0705e421d904bcd24405600b4":{
      "scriptId":"u105"},
    "009027c8d46d4374973354a3985f6cbe":{
      "scriptId":"u106"},
    "ffa241ff301843bc8ee78d205d81a3e4":{
      "scriptId":"u107"},
    "eb67ad2078694d05a0fa5077ac64f1ab":{
      "scriptId":"u108"},
    "10d0836155174346b7b4806b0fc2cb1c":{
      "scriptId":"u109"},
    "d16bf0e0d18e495cbeb42b6a4e2c8f33":{
      "scriptId":"u110"},
    "5e26e618ba4744a9ac1a5331703683de":{
      "scriptId":"u111"},
    "2803da4999b044c688e8cf92f197bf1d":{
      "scriptId":"u112"},
    "fb85c2b144dd4d758fd56af37ffa3ea2":{
      "scriptId":"u113"},
    "d10daccf51c44097bbfc96ccf2d93d81":{
      "scriptId":"u114"},
    "d549d507c2814bf59f6bb5f7d59a879b":{
      "scriptId":"u115"},
    "2a0d248213284c9086426dd1e0dd29f1":{
      "scriptId":"u116"},
    "bce99a6a245e47d98c3929ca124b32e1":{
      "scriptId":"u117"},
    "8a9cfc7017124bb99134e0dac64a7667":{
      "scriptId":"u118"},
    "a9c68eb906f14515afb73d46221b92d4":{
      "scriptId":"u119"},
    "372f9368a4694fdabc89f0808b745a31":{
      "scriptId":"u120"},
    "050179aa44994bd3b1c023ba186249c5":{
      "scriptId":"u121"},
    "1402eeee137b4af3b3c203f608c30ce8":{
      "scriptId":"u122"},
    "3669875cd7e44decb1bd2334c3d1df7e":{
      "scriptId":"u123"},
    "1d6e01d1ffc740c7a24478bb908f1116":{
      "scriptId":"u124"},
    "1ccf0226f1414fbe9980b769341643de":{
      "scriptId":"u125"}}});